---
- name: Deployment Otomatis Bahy - SIJA Kelas XI
  hosts: vm2
  become: yes
  tasks:
    # FASE 1: INSTALASI
    - name: 1. Update & Install Docker
      apt: { name: [docker.io, docker-compose-v2], state: present, update_cache: yes }

    # FASE 2: SETUP REPO
    - name: 2. Clone Repository
      git:
        repo: 'https://github.com/kucinggoreng-sys/parkir.git'
        dest: /opt/parkir_bahy
        force: yes

    # FASE 3: KONFIGURASI OTOMATIS (Sesuai Indikator 1 & 2)
    - name: 3. Setup .env
      copy: { src: /opt/parkir_bahy/.env.example, dest: /opt/parkir_bahy/.env, remote_src: yes }

    - name: 4. Patching UserFactory (Bypass Error Kelas Faker)
      shell: |
        cat << 'EOF' > /opt/parkir_bahy/database/factories/UserFactory.php
        <?php
        namespace Database\Factories;
        use Illuminate\Database\Eloquent\Factories\Factory;
        class UserFactory extends Factory {
            public function definition(): array {
                $r = rand(100, 999);
                return ['name' => 'Bahy_'.$r, 'email' => 'bahy'.$r.'@test.com', 'password' => bcrypt('password')];
            }
        }
        EOF

    # FASE 4: DOCKER ORCHESTRATION (Indikator 2)
    - name: 5. Build & Scaling Kontainer (3 Replika)
      shell: "docker compose up -d --scale nginx_bahy=3 --build"
      args: { chdir: /opt/parkir_bahy }

    # FASE 5: FINALISASI DATABASE
    - name: 6. Migrasi & Seed
      shell: "docker exec parkir_bahy-app_bahy-1 php artisan migrate:fresh --seed"~
