version: '3.8'

services:
  app_bahy:
    build: .
    image: laravel_parkir_bahy
    restart: always
    networks:
      - parkir_net_bahy

  db_bahy:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: db_parkir_bahy
      MYSQL_ROOT_PASSWORD: rahasia_bahy
    networks:
      - parkir_net_bahy

  nginx_bahy:
    image: nginx:latest
    restart: always
    ports:
      - "8001-8003:80"
    volumes:
      - .:/var/www:ro
      - ./nginx-bahy.conf:/etc/nginx/conf.d/default.conf
    networks:
      - parkir_net_bahy
    depends_on:
      - app_bahy

networks:
  parkir_net_bahy:
    driver: bridge
