version: '3.8'

services:
  web-bahy:
    container_name: web-bahy
    build: .
    restart: always
    networks:
      - asat-net

  db-bahy:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: db_parkir_bahy
      MYSQL_ROOT_PASSWORD: rahasia_bahy
    volumes:
      - asat-vol:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - asat-net

  nginx_bahy:
    image: nginx:latest
    restart: always
    ports:
      - "8001-8003:80"
    volumes:
      - .:/var/www
      - ./nginx-bahy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - asat-net
    depends_on:
      - web-bahy

networks:
  asat-net:
    driver: bridge
volumes:
  asat-vol:
